-- AlterTable
ALTER TABLE "userAluno" ADD COLUMN     "pointEasy" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pointHard" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pointMedium" INTEGER NOT NULL DEFAULT 0;
